routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => 'pickup.delivery.boy'], function(){

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\PickupBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\PickupBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-boy', 'as' => 'delivery.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\DeliveryBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\DeliveryBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });

    Route::group(['prefix' => 'user-management'], function() {
        });
});

Route::group(['middleware' => 'pickup.delivery.client'], function(){

    Route::group(['prefix' => 'pickup-client', 'as' => 'pickup.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\PickupClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\PickupClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\PickupClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-client', 'as' => 'delivery.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\DeliveryClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\DeliveryClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\DeliveryClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin-laundry', 'as' => 'admin.laundry.'], function () {
    Route::get('/', 'AdminLaundryController@index')->name('index');

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function(){
        Route::get('/', 'Admin\PickupDeliveryController@index')->name('index');
        Route::get('create', 'Admin\PickupDeliveryController@create')->name('create');
        Route::post('save', 'Admin\PickupDeliveryController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\PickupDeliveryController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\PickupDeliveryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PickupDeliveryController@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'client', 'as' => 'client.'], function(){
        Route::get('/', 'Admin\ClientController@index')->name('index');
        Route::get('create', 'Admin\ClientController@create')->name('create');
        Route::post('create/save', 'Admin\ClientController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\ClientController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\ClientController@update')->name('update');
        Route::post('delete/{id}', 'Client@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'kontrak', 'as' => 'kontrak.'], function(){
        Route::get('/', 'Admin\KontrakController@index')->name('index');
        Route::get('create', 'Admin\KontrakController@create')->name('create');
        Route::post('create/save', 'Admin\KontrakController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\KontrakController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\KontrakController@update')->name('update');
        Route::get('delete/{id}', 'Admin\KontrakController@delete')->name('delete');
        Route::get('getItem', 'Admin\KontrakController@create')->name('getItem');
    });
    
});

// Route::get('/home', 'PickupBoyController@index')->name('home');

// AJAX
Route::post('/ajax/get-item', 'AjaxController@getItem')->name('getItem');
Route::post('/ajax/get-item-client', 'AjaxController@getItemClient')->name('getItemClient');
Route::post('/ajax/get-item-del-client', 'AjaxController@getItemClient')->name('getItemClient');

app/Http/Controllers/AdminLaundryController.php
<?php

namespace App\Http\Controllers;

use App\Model\AdminLaundry;
use Illuminate\Http\Request;

class AdminLaundryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin-laundry.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
        /**
     * Display the specified resource.
     *
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
    public function show(AdminLaundry $adminLaundry)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
    public function edit(AdminLaundry $adminLaundry)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AdminLaundry $adminLaundry)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
}

app/Http/Controllers/PickupDeliveryBoy/PickupBoyController.php
<?php

namespace App\Http\Controllers\PickupDeliveryBoy;

use App\Model\PickupBoy;
use App\Model\PickupClient;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PickupBoyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = PickupClient::where('status', 'r')->get();
        $dataClose = PickupClient::where('status', 'a')->get();
        return view('pickup-boy.index', compact('data', 'dataClose'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\PickupBoy  $pickupBoy
     * @return \Illuminate\Http\Response
     */
    public function show(PickupBoy $pickupBoy)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\PickupBoy  $pickupBoy
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $edit = PickupClient::where('id', $id)->first();
        $editItem = PickupClient::select('item_code', 'item_name', 'qty')->where('id', $id)->get();
        
        if ($request->isMethod('POST')) 
        {
            // dd($request->qty);
            PickupClient::where('id', $id)->update([
                'status' => 'a',
                'qty' => json_encode($request->qty),
            ]);

            return redirect('pickup-boy')->with('success', 'Data Berhasil Diapprove');
        }

        return view('pickup-boy.edit', compact('edit', 'editItem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\PickupBoy  $pickupBoy
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PickupBoy $pickupBoy)
    { 
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\PickupBoy  $pickupBoy
     * @return \Illuminate\Http\Response
     */
    public function destroy(PickupBoy $pickupBoy)
    {
        //
    }
}

resources/views/admin-laundry/pickup-boy/create.blade.php
@php
    $date = date('Y-m-d');    
    $jam = date('H:i:s');    
@endphp

@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Pickup Service - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.index') }}">Dashboard</a>
			</div>
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.pickup.boy.index') }}">Pickup Boy</a>
			</div>
			<div class="breadcrumb-item active">
				<a>Create</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('/admin') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('admin.laundry.pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup & Delivery Boy"><i class="fas fa-user"></i><span>Pickup & Delivery Boy</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Client"><i class="fas fa-user"></i><span>Maintenance Client</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Kontrak"><i class="fas fa-file"></i><span>Maintenance Kontrak</span></a></li>
    <li><a class="nav-link" href="{{ route('users') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Management User"><i class="fas fa-users"></i><span>Management User</span></a></li>
   </ul>
@endsection

@section('content')
<form action="{{ route('admin.laundry.pickup.boy.store') }}" method="POST">
    @csrf
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
        
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="" >
                        </div>
                    </div>    
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">HP</label>
                        <div class="col-md-7">
                            <input type="text" name="hp" class="form-control" required="" value="" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Sex</label>
                        <div class="col-md-7">
                            <input type="text" name="sex" class="form-control" required="" value="" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Alamat</label>
                        <div class="col-md-7">
                            <textarea name="alamat" class="form-control" id="" cols="30" rows="10"></textarea>
                        </div>
                    </div>   
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pekerjaan</label>
                        <div class="col-md-7">
                            <input type="text" name="pekerjaan" class="form-control" required="" value="" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Agama</label>
                        <div class="col-md-7">
                            <input type="agama" name="agama" class="form-control" required="" value="" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tgl Lahir</label>
                        <div class="col-md-7">
                            <input type="date" name="tgl_lahir" class="form-control" required="" value="" >
                        </div>
                    </div>  
                        
                </div>
            
                <div class="col-md-6">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Suku</label>
                        <div class="col-md-7">
                            <input type="text" name="suku" class="form-control" required="" value="" >
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Provinsi</label>
                        <div class="col-md-7">
                            <input type="text" name="provinsi" class="form-control" required="" value="" >
                        </div>
                    </div>
                    
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kabupaten</label>
                        <div class="col-md-7">
                            <input type="text" name="kabupaten" class="form-control" required="" value="" >
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kecamatan</label>
                        <div class="col-md-7">
                            <input type="text" name="kecamatan" class="form-control" required="" value="" >
                        </div>
                    </div>
                        <div class="card-footer text-right">
                            <a href="{{ route('admin.laundry.pickup.boy.index') }}" class="btn btn-danger btn-lg">Batal</a>
                            <button class="btn btn-primary btn-lg">Simpan</button>
                        </div>
                    </form>
                    
                </div>
      </div>
    </div>
</div>
@endsection

resources/views/admin-laundry/pickup-boy/edit.blade.php
@php
    $date = date('Y-m-d');    
    $jam = date('H:i:s');    
@endphp

@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Pickup Service - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.index') }}">Dashboard</a>
			</div>
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.pickup.boy.index') }}">Pickup Boy</a>
			</div>
			<div class="breadcrumb-item active">
				<a>Edit</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('/admin') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('admin.laundry.pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup & Delivery Boy"><i class="fas fa-user"></i><span>Pickup & Delivery Boy</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Client"><i class="fas fa-user"></i><span>Maintenance Client</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Kontrak"><i class="fas fa-file"></i><span>Maintenance Kontrak</span></a></li>
    <li><a class="nav-link" href="{{ route('users') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Management User"><i class="fas fa-users"></i><span>Management User</span></a></li>
   </ul>
@endsection

@section('content')

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
        <form action="{{ url('admin-laundry/pickup-boy/update/'.$edit->id) }}">
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="{{ $edit->nama }}" >
                        </div>
                    </div>    
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">HP</label>
                        <div class="col-md-7">
                            <input type="text" name="hp" class="form-control" required="" value="{{ $edit->hp }}" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Sex</label>
                        <div class="col-md-7">
                            <input type="text" name="sex" class="form-control" required="" value="{{ $edit->sex }}" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Alamat</label>
                        <div class="col-md-7">
                        <textarea name="alamat" class="form-control" id="" cols="30" rows="10">{{ $edit->alamat }}</textarea>
                        </div>
                    </div>   
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pekerjaan</label>
                        <div class="col-md-7">
                            <input type="text" name="pekerjaan" class="form-control" required="" value="{{ $edit->pekerjaan }}" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Agama</label>
                        <div class="col-md-7">
                            <input type="agama" name="agama" class="form-control" required="" value="{{ $edit->agama }}" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tgl Lahir</label>
                        <div class="col-md-7">
                            <input type="date" name="tgl_lahir" class="form-control" required="" value="{{ $edit->tgl_lahir }}" >
                        </div>
                    </div>  
                        
                </div>
            
                <div class="col-md-6">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Suku</label>
                        <div class="col-md-7">
                            <input type="text" name="suku" class="form-control" required="" value="{{ $edit->suku }}" >
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Provinsi</label>
                        <div class="col-md-7">
                            <input type="text" name="provinsi" class="form-control" required="" value="{{ $edit->provinsi }}" >
                        </div>
                    </div>
                    
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kabupaten</label>
                        <div class="col-md-7">
                            <input type="text" name="kabupaten" class="form-control" required="" value="{{ $edit->kabupaten }}" >
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kecamatan</label>
                        <div class="col-md-7">
                            <input type="text" name="kecamatan" class="form-control" required="" value="{{ $edit->kecamatan }}" >
                        </div>
                    </div>
                        <div class="card-footer text-right">
                            <a href="{{ route('admin.laundry.pickup.boy') }}" class="btn btn-danger btn-lg">Batal</a>
                            <button class="btn btn-primary btn-lg">Simpan</button>
                        </div>
                    </form>
                    
                </div>
      </div>
    </div>
</div>
@endsection

resources/views/admin-laundry/pickup-boy/index.blade.php
@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Pickup Deliver - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ url('admin') }}">Dashboard</a>
			</div>
			<div class="breadcrumb-item active">
				<a>Pickup Boy</a>
			</div>
		</div>
	</div>
@endsection

@section('sidebar-menu')
<ul class="sidebar-menu">
  <li class="menu-header">Dashboard</li>
  <li><a class="nav-link" href="{{ url('/admin') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
  <li class="menu-header">List</li>
  <li><a class="nav-link" href="{{ route('admin.laundry.pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup & Delivery Boy"><i class="fas fa-user"></i><span>Pickup & Delivery Boy</span></a></li>
  <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Client"><i class="fas fa-user"></i><span>Maintenance Client</span></a></li>
  <li><a class="nav-link" href="{{ route('admin.laundry.kontrak.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Kontrak"><i class="fas fa-file"></i><span>Maintenance Kontrak</span></a></li>
  <li><a class="nav-link" href="{{ route('users') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Management User"><i class="fas fa-users"></i><span>Management User</span></a></li>
</ul>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">  
              <table class="table table-bordered table-striped table-hover" id="dabel">
                <a href="{{ route('admin.laundry.pickup.boy.create') }}" class="a btn btn-info btn-lg float-right"><i class="fa fa-plus"></i></a>
                <br>
                <h4 class="card-title">Maintenance Pickup-Delivery Boy</h4>

                  <thead class="text-center">
                      <tr>
                          <th>No</th>
                          <th>Nama</th>
                          <th>No Hp</th>
                          <th>Sex</th>
                          <th>Alamat</th>
                          <th>Pekerjaan</th>
                          <th>Agama</th>
                          <th>Tgl Lahir</th>
                          <th>Action</th>
                      </tr>
                  </thead>
                  <tbody>
                      @foreach ($data as $val)
                          <tr>
                            <td>{{ $loop->index+1 }}</td>
                            <td>{{ $val->nama }}</td>
                            <td>{{ $val->hp }}</td>
                            <td>{{ $val->sex }}</td>
                            <td>{{ $val->alamat }}</td>
                            <td>{{ $val->pekerjaan }}</td>
                            <td>{{ $val->agama }}</td>
                            <td>{{ $val->tgl_lahir }}</td>
                            <td>
                              <a href="{{ url('admin-laundry/pickup-boy/edit/'.$val->id) }}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                              <a href="{{ url('admin-laundry/pickup-boy/delete/'.$val->id) }}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            </td>
                          </tr>
                      @endforeach
                  </tbody>
              </table>  
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection