routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => 'pickup.delivery.boy'], function(){

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\PickupBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\PickupBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-boy', 'as' => 'delivery.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\DeliveryBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\DeliveryBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });

    Route::group(['prefix' => 'user-management'], function() {
        });
});

Route::group(['middleware' => 'pickup.delivery.client'], function(){

    Route::group(['prefix' => 'pickup-client', 'as' => 'pickup.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\PickupClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\PickupClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\PickupClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-client', 'as' => 'delivery.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\DeliveryClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\DeliveryClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\DeliveryClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin-laundry', 'as' => 'admin.laundry.'], function () {
    Route::get('/', 'AdminLaundryController@index')->name('index');

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function(){
        Route::get('/', 'Admin\PickupDeliveryController@index')->name('index');
        Route::get('create', 'Admin\PickupDeliveryController@create')->name('create');
        Route::post('save', 'Admin\PickupDeliveryController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\PickupDeliveryController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\PickupDeliveryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PickupDeliveryController@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'client', 'as' => 'client.'], function(){
        Route::get('/', 'Admin\ClientController@index')->name('index');
        Route::get('create', 'Admin\ClientController@create')->name('create');
        Route::post('create/save', 'Admin\ClientController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\ClientController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\ClientController@update')->name('update');
        Route::post('delete/{id}', 'Client@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'kontrak', 'as' => 'kontrak.'], function(){
        Route::get('/', 'Admin\KontrakController@index')->name('index');
        Route::get('create', 'Admin\KontrakController@create')->name('create');
        Route::post('create/save', 'Admin\KontrakController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\KontrakController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\KontrakController@update')->name('update');
        Route::get('delete/{id}', 'Admin\KontrakController@delete')->name('delete');
        Route::get('getItem', 'Admin\KontrakController@create')->name('getItem');
    });
    
});

// Route::get('/home', 'PickupBoyController@index')->name('home');

// AJAX
Route::post('/ajax/get-item', 'AjaxController@getItem')->name('getItem');
Route::post('/ajax/get-item-client', 'AjaxController@getItemClient')->name('getItemClient');
Route::post('/ajax/get-item-del-client', 'AjaxController@getItemClient')->name('getItemClient');

app/Http/Controllers/PickupDeliveryClient/DeliveryClientController.php
<?php

namespace App\Http\Controllers\PickupDeliveryClient;

use Illuminate\Http\Request;
use App\Model\DeliveryClient;
use App\Model\PickupClient;
use App\Http\Controllers\Controller;

class DeliveryClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DeliveryClient::all();
        return view('delivery-client.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // dd($request->isMethod('POST'));
        if ($request->isMethod('POST')) 
        {
            // dd($request->isMethod('POST'));
            $request->validate([
                'rumah_sakit' => 'required',
                'lantai' => 'required',
                'ruang_perawatan' => 'required',
                'pic' => 'required',
                'tanggal' => 'required',
                'item_code' => 'required',
                'item_name' => 'required',
                'qty' => 'required',
                'pickup_boy' => 'required',
                'jam' => 'required',
            ]);
            
            DeliveryClient::create([
                'rumah_sakit' => $request->rumah_sakit,
                'lantai' => $request->lantai,
                'ruang_perawatan' => $request->ruang_perawatan,
                'pic' => $request->pic,
                'tanggal' => $request->tanggal,
                'item_code' => json_encode($request->item_code),
                'item_name' => json_encode($request->item_name),
                'qty' => json_encode($request->qty),
                'pickup_boy' => $request->pickup_boy,
                'jam' => $request->jam,
            ]);

            return redirect('delivery-client')->with('success', 'Data Berhasil Ditambahkan');
        }

        return view('delivery-client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $edit = DeliveryClient::where('id', $id)->first();
        $editItem = DeliveryClient::select('item_code', 'item_name', 'qty')->where('id', $id)->get();
        
        if ($request->isMethod('POST')) 
        {
            DeliveryClient::where('id', $id)->update([
                'status' => 'd',
            ]);

            return redirect('delivery-client')->with('success', 'Data Berhasil Diapprove');
        }

        return view('delivery-client.edit', compact('edit', 'editItem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/delivery-client/addItem.blade.php
<div class="row" style="margin-top:10px" id="input-{{ $key }}">
    <div class="col-md-1"></div>
    <div class="col-md-2">
        <input type="text" class="form-control" name="item_code[{{ $key }}]" id="myorders">
    </div>
    <div class="col-md-4">
        <input type="text" class="form-control" name="item_name[{{ $key }}]" id="myorders">
    </div>
    <div class="col-md-2">
        <input type="number" class="form-control" name="qty[{{ $key }}]" id="myorders">
    </div>
    <div class="col-md-1">
        <button type="button" class="btn btn-danger" onclick="$(this).removeItem('#input-{{ $key }}')">x</button>
    </div>
</div>

resources/views/delivery-client/create.blade.php
@php
    $date = date('Y-m-d');    
    $jam = date('H:i:s');    
@endphp

@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Delivery Service - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ url('admin') }}">Dashboard</a>
			</div>
		</div>
	</div>
@endsection
        
@section('sidebar-menu')
<ul class="sidebar-menu">
  <li class="menu-header">Dashboard</li>
  <li><a class="nav-link" href="{{ url('pickup-client') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
  <li class="menu-header">List</li>
  <li><a class="nav-link" href="{{ route('pickup.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup Client"><i class="fas fa-file"></i><span>Pickup Client</span></a></li>
  <li><a class="nav-link" href="{{ route('delivery.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Delivery Client"><i class="fas fa-file"></i><span>Delivery Client</span></a></li>
</ul>
@endsection

@section('content')
<form action="{{ route('delivery.client.create') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Rumah Sakit</label>
                            <div class="col-md-7">
                                <input type="text" name="rumah_sakit" class="form-control" required="" value="" >
                            </div>
                        </div>    
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Lantai</label>
                            <div class="col-md-7">
                                <input type="text" name="lantai" class="form-control" required="" value="" >
                            </div>
                        </div>  
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Ruang Perawatan</label>
                            <div class="col-md-7">
                                <input type="text" name="ruang_perawatan" class="form-control" required="" value="" >
                            </div>
                        </div>  
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">PIC</label>
                            <div class="col-md-7">
                                <input type="text" name="pic" class="form-control" required="" value="" >
                            </div>
                        </div>   
                            
                    </div>
                
                    <div class="col-md-6">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tanggal</label>
                            <div class="col-md-7">
                                <input type="text" name="tanggal" class="form-control" required="" value="{{$date}}" readonly>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <div>
                    <hr>
                </div>
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-2">
                            <h6 class="text-center">Item Code</h6>
                            <input type="text" class="form-control" name="item_code[0]" id="myorders">
                        </div>
                        <div class="col-md-4">
                            <h6 class="text-center">Item Name</h6>
                            <input type="text" class="form-control" name="item_name[0]" id="myorders">
                        </div>
                        <div class="col-md-2">
                            <h6 class="text-center">Qty</h6>
                            <input type="number" class="form-control" name="qty[0]" id="myorders">
                        </div>
                        <div class="col-md-1">
                            <button type="button" class="btn btn-success" id="add-item"><i class="fa fa-plus"></i></button>
                        </div>
                    </div>

                    {{-- append ajax --}}
                    <div id="input-list"> </div>
                    <input type="hidden" id="key" value="0">
                    <br>

                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-4">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pickup Boy</label>
                            <div class="col-md-7">
                                <input type="text" name="pickup_boy" class="form-control" required="">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jam</label>
                            <div class="col-md-7">
                            <input type="text" name="jam" class="form-control" value="{{ $jam }}" required="">
                            </div>
                        </div>
                    </div>
                    <form action="{{ route('pickup.client.create') }}">
                        <div class="col-md-1">
                            <button class="btn btn-success btn-lg">Submit</button>
                        </div>
                    </form>
                    
                </div>
                
        </div>
        </div>
    </div>
</form>
@endsection

@section('script')
  
    <script>
        $(document).ready(function(){

            var key_input = $("#key").val();

            $("#add-item").on("click", function(e){ 

                e.preventDefault();

                key_input++;

                var url = '/ajax/get-item-del-client'

                var data = {
                    key:key_input
                }
                
                $.ajax({
                    url:url,
                    data:data,
                    type:"POST",
                    success:function(result){
                        $("#input-list").append(result.html);
                        $("#key").val(result.key);
                    }
                })
            
            });
        });

        $.fn.removeItem = function(id){
            $(id).remove();
        }

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        
    </script>

@endsection

resources/views/delivery-client/edit.blade.php
@php
    $date = date('Y-m-d');    
    $jam = date('H:i:s');    
@endphp

@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Delivery Service - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ url('admin') }}">Dashboard</a>
			</div>
		</div>
	</div>
@endsection
    
@section('content')kmkmm
<form action="{{ url('delivery-client/edit/'.$edit->id) }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Rumah Sakit</label>
                            <div class="col-md-7">
                                <input type="text" name="rumah_sakit" class="form-control" readonly value="{{ $edit->rumah_sakit }}" >
                            </div>
                        </div>    
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Lantai</label>
                            <div class="col-md-7">
                                <input type="text" name="lantai" class="form-control" readonly value="{{ $edit->lantai }}" >
                            </div>
                        </div>  
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Ruang Perawatan</label>
                            <div class="col-md-7">
                                <input type="text" name="ruang_perawatan" class="form-control" readonly value="{{ $edit->ruang_perawatan }}" >
                            </div>
                        </div>  
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">PIC</label>
                            <div class="col-md-7">
                                <input type="text" name="pic" class="form-control" readonly value="{{ $edit->pic }}" >
                            </div>
                        </div>   
                            
                    </div>
                
                    <div class="col-md-6">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tanggal</label>
                            <div class="col-md-7">
                                <input type="text" name="tanggal" class="form-control" value="{{$edit->tanggal}}" readonly>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <div>
                    <hr>
                    @foreach ($editItem as $item)
                        @php
                            $kode = json_decode($item->item_code);
                            $nama = json_decode($item->item_name);
                            $qty = json_decode($item->qty);
                            // dd($nama);
                        @endphp
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-2">
                                    <h6 class="text-center">Item Code</h6>
                                    @foreach ($kode as $val)
                                        <input type="text" class="form-control" value="{{ $val }}" readonly name="item_code[]"><br>
                                    @endforeach
                                </div>
                                <div class="col-md-4">
                                    <h6 class="text-center">Item Name</h6>
                                    @foreach ($nama as $val)
                                        <input type="text" class="form-control" value="{{ $val }}" readonly name="nama_item[]"><br>
                                    @endforeach
                                </div>
                                <div class="col-md-2">
                                    <h6 class="text-center">Qty</h6>
                                    @foreach ($qty as $val)
                                        <input type="number" class="form-control" value="{{ $val }}" readonly name="qty[]"><br>
                                    @endforeach
                                </div>
                                {{-- <div class="col-md-1">
                                    <button type="button" class="btn btn-success" id="add-item"><i class="fa fa-plus"></i></button>
                                </div> --}}

                                {{-- <div class="col-md-1">
                                    <button type="button" class="btn btn-success" id="add-order"><i class="fa fa-plus"></i></button>
                                </div> --}}
                            </div>
                    @endforeach
                </div>

                    {{-- append ajax --}}
                    <div id="input-list"> </div>
                    <input type="hidden" id="key" value="0">
                    <br>

                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-4">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pickup Boy</label>
                            <div class="col-md-7">
                                <input type="text" name="pickup_boy" class="form-control" readonly value="{{ $edit->pickup_boy }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jam</label>
                            <div class="col-md-7">
                            <input type="text" name="jam" class="form-control" value="{{ $jam }}" readonly value="{{ $edit->jam }}">
                            </div>
                        </div>
                    </div>
                    <form action="{{ route('pickup.client.create') }}">
                        <div class="col-md-1">
                            <button class="btn btn-success btn-lg">Approval</button>
                        </div>
                    </form>
                    
                </div>
                
        </div>
        </div>
    </div>
</form>
@endsection

@section('script')
  
    <script>
        $(document).ready(function(){

            var key_input = $("#key").val();

            $("#add-item").on("click", function(e){ 

                e.preventDefault();

                key_input++;

                var url = '/ajax/get-item-client'

                var data = {
                    key:key_input
                }
                
                $.ajax({
                    url:url,
                    data:data,
                    type:"POST",
                    success:function(result){
                        $("#input-list").append(result.html);
                        $("#key").val(result.key);
                    }
                })
            
            });
        });

        $.fn.removeItem = function(id){
            $(id).remove();
        }

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        
    </script>

@endsection

resources/views/delivery-client/index.blade.php
@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Pickup Service - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ url('pickup-client') }}">Dashboard</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('pickup-client') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('pickup.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup Client"><i class="fas fa-file"></i><span>Pickup Client</span></a></li>
    <li><a class="nav-link" href="{{ route('pickup.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Delivery Client"><i class="fas fa-file"></i><span>Delivery Client</span></a></li>
  </ul>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
            <a href="{{ route('delivery.client.create') }}" class="btn btn-info btn-lg float-right"><i class="fa fa-plus"></i></a>
                <br>
                <table class="table table-bordered table-striped table-hover" id="dabel">
                  <h4 class="card-title">List Of Order</h4>

                    <thead class="text-center">
                        <tr>
                            <th>No</th>
                            <th>Rumah Sakit</th>
                            <th>Lantai</th>
                            <th>Ruang Perawatan</th>
                            <th>PIC</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @foreach ($data as $val)
                            <tr>
                              <td>{{ $loop->index+1 }}</td>
                              <td>{{ $val->rumah_sakit }}</td>
                              <td>{{ $val->lantai }}</td>
                              <td>{{ $val->ruang_perawatan }}</td>
                              <td>{{ $val->pic }}</td>
                              <td>
                                @if ($val->status == 's')
                                    <div class="badge badge-warning">S</div>
                                @elseif($val->status == 'r')
                                    <div class="badge badge-info">R</div>
                                  @elseif($val->status == 'd')
                                      <div class="badge badge-info">D</div>
                                @endif
                              </td>
                              <td>
                                <a href="{{ url('delivery-client/edit/'.$val->id) }}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                              </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table> 
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection