routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => 'pickup.delivery.boy'], function(){

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\PickupBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\PickupBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-boy', 'as' => 'delivery.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\DeliveryBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\DeliveryBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });

    Route::group(['prefix' => 'user-management'], function() {
        });
});

Route::group(['middleware' => 'pickup.delivery.client'], function(){

    Route::group(['prefix' => 'pickup-client', 'as' => 'pickup.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\PickupClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\PickupClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\PickupClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-client', 'as' => 'delivery.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\DeliveryClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\DeliveryClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\DeliveryClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin-laundry', 'as' => 'admin.laundry.'], function () {
    Route::get('/', 'AdminLaundryController@index')->name('index');

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function(){
        Route::get('/', 'Admin\PickupDeliveryController@index')->name('index');
        Route::get('create', 'Admin\PickupDeliveryController@create')->name('create');
        Route::post('save', 'Admin\PickupDeliveryController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\PickupDeliveryController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\PickupDeliveryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PickupDeliveryController@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'client', 'as' => 'client.'], function(){
        Route::get('/', 'Admin\ClientController@index')->name('index');
        Route::get('create', 'Admin\ClientController@create')->name('create');
        Route::post('create/save', 'Admin\ClientController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\ClientController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\ClientController@update')->name('update');
        Route::post('delete/{id}', 'Client@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'kontrak', 'as' => 'kontrak.'], function(){
        Route::get('/', 'Admin\KontrakController@index')->name('index');
        Route::get('create', 'Admin\KontrakController@create')->name('create');
        Route::post('create/save', 'Admin\KontrakController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\KontrakController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\KontrakController@update')->name('update');
        Route::get('delete/{id}', 'Admin\KontrakController@delete')->name('delete');
        Route::get('getItem', 'Admin\KontrakController@create')->name('getItem');
    });
    
});

// Route::get('/home', 'PickupBoyController@index')->name('home');

// AJAX
Route::post('/ajax/get-item', 'AjaxController@getItem')->name('getItem');
Route::post('/ajax/get-item-client', 'AjaxController@getItemClient')->name('getItemClient');
Route::post('/ajax/get-item-del-client', 'AjaxController@getItemClient')->name('getItemClient');

app/Http/Controllers/PickupDeliveryBoy/DeliveryBoyController.php
<?php

namespace App\Http\Controllers\PickupDeliveryBoy;

use Illuminate\Http\Request;
use App\Model\DeliveryBoy;
use App\Model\DeliveryClient;
use App\Http\Controllers\Controller;

class DeliveryBoyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DeliveryClient::where('status', 's')->get();
        $dataClose = DeliveryClient::where('status', 'r')->get();
        return view('delivery-boy.index', compact('data', 'dataClose'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $edit = DeliveryClient::where('id', $id)->first();
        $editItem = DeliveryClient::select('item_code', 'item_name', 'qty')->where('id', $id)->get();
        
        if ($request->isMethod('POST')) 
        {
            // dd($request->qty);
            DeliveryClient::where('id', $id)->update([
                'status' => 'r',
                'qty' => json_encode($request->qty),
            ]);

            return redirect('delivery-boy')->with('success', 'Data Berhasil Diapprove');
        }

        return view('delivery-boy.edit', compact('edit', 'editItem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/delivery-boy/edit.blade.php
@php
    $date = date('Y-m-d');
@endphp
@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Pickup Service - Transaksi</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ url('admin') }}">Transaksi</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('pickup-boy') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup Boy"><i class="fas fa-file"></i><span>Pickup Boy</span></a></li>
    <li><a class="nav-link" href="{{ route('delivery.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Delivery Boy"><i class="fas fa-file"></i><span>Delivery Boy</span></a></li>
  </ul>
@endsection

@section('content')
<form action="{{ url('delivery-boy/edit/'.$edit->id) }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-12">
        <div class="card">
            <div class="card-body">
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Rumah Sakit</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="{{$edit->rumah_sakit}}" readonly>
                        </div>
                    </div>    
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Lantai</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="{{$edit->lantai}}" readonly>
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Ruang Perawatan</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="{{$edit->ruang_perawatan}}" readonly>
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">PIC</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="{{$edit->pic}}" readonly>
                        </div>
                    </div>   
                        
                </div>

                <div class="col-md-6">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tanggal</label>
                        <div class="col-md-7">
                            <input type="text" name="nama" class="form-control" required="" value="{{$date}}" readonly>
                        </div>
                    </div>
                    
                </div>
                
                <div class="col-12">
                    <hr>
                </div>
                
                @foreach ($editItem as $item)
                    @php
                        $kode = json_decode($item->item_code);
                        $nama = json_decode($item->item_name);
                        $qty = json_decode($item->qty);
                        // dd($nama);
                    @endphp
                        <div class="row">
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                                <h6 class="text-center">Item Code</h6>
                                @foreach ($kode as $val)
                                    <input type="text" class="form-control" value="{{ $val }}" readonly name="item_code[0]"><br>
                                @endforeach
                            </div>
                            <div class="col-md-6">
                                <h6 class="text-center">Item Name</h6>
                                @foreach ($nama as $val)
                                    <input type="text" class="form-control" value="{{ $val }}" readonly name="nama_item[0]"><br>
                                @endforeach
                            </div>
                            <div class="col-md-2">
                                <h6 class="text-center">Qty</h6>
                                @foreach ($qty as $val)
                                    <input type="number" class="form-control" value="{{ $val }}" name="qty[]" readonly><br>
                                @endforeach
                            </div>
                        </div>
                @endforeach
            </div>
            <br>

            <div class="card-footer text-right">
                <button class="btn btn-primary btn-lg">Drop</button>
            </div>
        </div>
        </div>
    </div>
</form>

@endsection

resources/views/delivery-boy/index.blade.php
@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Delivery Service - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ url('admin') }}">Dashboard</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('pickup-boy') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup Boy"><i class="fas fa-file"></i><span>Pickup Boy</span></a></li>
    <li><a class="nav-link" href="{{ route('delivery.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Delivery Boy"><i class="fas fa-file"></i><span>Delivery Boy</span></a></li>
  </ul>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered table-striped table-hover" id="dabel">
                  <h4 class="card-title">List Order Open</h4>

                    <thead class="text-center">
                        <tr>
                            <th>No</th>
                            <th>Rumah Sakit</th>
                            <th>Lantai</th>
                            <th>Ruang Perawatan</th>
                            <th>PIC</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $val)
                            <tr>
                              <td>{{ $loop->index+1 }}</td>
                              <td>{{ $val->rumah_sakit }}</td>
                              <td>{{ $val->lantai }}</td>
                              <td>{{ $val->ruang_perawatan }}</td>
                              <td>{{ $val->pic }}</td>
                              <td>
                                  @if ($val->status == 's')
                                      <div class="badge badge-warning">S</div>
                                  @else
                                      <div class="badge badge-warning">R</div>
                                  @endif
                              </td>
                              <td>
                                <a href="{{ url('delivery-boy/edit/'.$val->id) }}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                              </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>   
                
                <div>
                  <hr>
                </div>
                
                <table class="table table-bordered table-hover" id="dabel">
                  <h4 class="card-title">List Order Close</h4>
                  <thead class="text-center">
                      <tr>
                          <th>No</th>
                          <th>Rumah Sakit</th>
                          <th>Lantai</th>
                          <th>Ruang Perawatan</th>
                          <th>PIC</th>
                          <th>Status</th>
                      </tr>
                  </thead>
                  <tbody>
                     @foreach ($dataClose as $val)
                        <tr>
                          <td>{{ $loop->index+1 }}</td>
                              <td>{{ $val->rumah_sakit }}</td>
                              <td>{{ $val->lantai }}</td>
                              <td>{{ $val->ruang_perawatan }}</td>
                              <td>{{ $val->pic }}</td>
                              <td>
                                  @if ($val->status == 'r')
                                      <div class="badge badge-success">D</div>
                                  @endif
                              </td>
                        </tr>
                    @endforeach
                      <tr>
                  </tbody>
              </table>   
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection