routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => 'pickup.delivery.boy'], function(){

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\PickupBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\PickupBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-boy', 'as' => 'delivery.boy.'], function () {
        Route::get('/', 'PickupDeliveryBoy\DeliveryBoyController@index')->name('index');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryBoy\DeliveryBoyController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });

    Route::group(['prefix' => 'user-management'], function() {
        });
});

Route::group(['middleware' => 'pickup.delivery.client'], function(){

    Route::group(['prefix' => 'pickup-client', 'as' => 'pickup.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\PickupClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\PickupClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\PickupClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'delivery-client', 'as' => 'delivery.client.'], function () {
        Route::get('/', 'PickupDeliveryClient\DeliveryClientController@index')->name('index');
        Route::match(['get', 'post'], 'create', 'PickupDeliveryClient\DeliveryClientController@create')->name('create');
        Route::match(['get', 'post'], 'edit/{id}', 'PickupDeliveryClient\DeliveryClientController@edit')->name('edit');
        Route::post('delete/{id}', 'PickupBoy@delete')->name('delete');
    });
});

Route::group(['middleware' => 'admin', 'prefix' => 'admin-laundry', 'as' => 'admin.laundry.'], function () {
    Route::get('/', 'AdminLaundryController@index')->name('index');

    Route::group(['prefix' => 'pickup-boy', 'as' => 'pickup.boy.'], function(){
        Route::get('/', 'Admin\PickupDeliveryController@index')->name('index');
        Route::get('create', 'Admin\PickupDeliveryController@create')->name('create');
        Route::post('save', 'Admin\PickupDeliveryController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\PickupDeliveryController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\PickupDeliveryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PickupDeliveryController@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'client', 'as' => 'client.'], function(){
        Route::get('/', 'Admin\ClientController@index')->name('index');
        Route::get('create', 'Admin\ClientController@create')->name('create');
        Route::post('create/save', 'Admin\ClientController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\ClientController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\ClientController@update')->name('update');
        Route::post('delete/{id}', 'Client@delete')->name('delete');
    });
    
    Route::group(['prefix' => 'kontrak', 'as' => 'kontrak.'], function(){
        Route::get('/', 'Admin\KontrakController@index')->name('index');
        Route::get('create', 'Admin\KontrakController@create')->name('create');
        Route::post('create/save', 'Admin\KontrakController@store')->name('store');
        Route::match(['get', 'post'], 'edit/{id}', 'Admin\KontrakController@edit')->name('edit');
        Route::match(['get', 'post'], 'update/{id}', 'Admin\KontrakController@update')->name('update');
        Route::get('delete/{id}', 'Admin\KontrakController@delete')->name('delete');
        Route::get('getItem', 'Admin\KontrakController@create')->name('getItem');
    });
    
});

// Route::get('/home', 'PickupBoyController@index')->name('home');

// AJAX
Route::post('/ajax/get-item', 'AjaxController@getItem')->name('getItem');
Route::post('/ajax/get-item-client', 'AjaxController@getItemClient')->name('getItemClient');
Route::post('/ajax/get-item-del-client', 'AjaxController@getItemClient')->name('getItemClient');

app/Http/Controllers/Admin/KontrakController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Kontrak;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class KontrakController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Kontrak::all();
        return view('admin-laundry.kontrak.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-laundry.kontrak.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'no_kontrak' => 'required',
            'client' => 'required',
            'periode_kontrak_mulai' => 'required',
            'periode_kontrak_akhir' => 'required|after_or_equal:periode_kontrak_mulai',
            'jenis_kegiatan' => 'required',
            'kuota_minimal' => 'required',
            'berat_minimal' => 'required',
            'periode_tagihan' => 'required',
            'jatuh_tempo' => 'required',
            'terbit_invoice' => 'required',
            'blokir_pickup' => 'required',
            'kode_item' => 'required',
            'nama_item' => 'required',
            'berat' => 'required',
            'harga' => 'required',
        ]);

        Kontrak::create([
            'no_kontrak' => $request->no_kontrak,
            'client' => $request->client,
            'periode_kontrak_mulai' => $request->periode_kontrak_mulai,
            'periode_kontrak_akhir' => $request->periode_kontrak_akhir,
            'jenis_kegiatan' => $request->jenis_kegiatan,
            'kuota_minimal' => $request->kuota_minimal,
            'berat_minimal' => $request->berat_minimal,
            'periode_tagihan' => $request->periode_tagihan,
            'jatuh_tempo' => $request->jatuh_tempo,
            'terbit_invoice' => $request->terbit_invoice,
            'blokir_pickup' => $request->blokir_pickup,
            'kode_item' => json_encode($request->kode_item),
            'nama_item' => json_encode($request->nama_item),
            'berat' => json_encode($request->berat),
            'harga' => json_encode($request->harga),
        ]);

        return redirect('admin-laundry/kontrak/create')->with('success', 'Data Berhasi Ditambahkan !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Kontrak  $kontrak
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Kontrak  $kontrak
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = Kontrak::where('id', $id)->first();
        $editItem = Kontrak::select('kode_item', 'nama_item', 'harga', 'berat')->where('id', $id)->get();

        return view('admin-laundry.kontrak.edit', compact('edit','editItem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Kontrak  $kontrak
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Kontrak::where('id', $id)->update([
            'no_kontrak' => $request->no_kontrak,
            'client' => $request->client,
            'periode_kontrak_mulai' => $request->periode_kontrak_mulai,
            'periode_kontrak_akhir' => $request->periode_kontrak_akhir,
            'jenis_kegiatan' => $request->jenis_kegiatan,
            'kuota_minimal' => $request->kuota_minimal,
            'berat_minimal' => $request->berat_minimal,
            'periode_tagihan' => $request->periode_tagihan,
            'jatuh_tempo' => $request->jatuh_tempo,
            'terbit_invoice' => $request->terbit_invoice,
            'blokir_pickup' => $request->blokir_pickup,
            'kode_item' => json_encode($request->kode_item),
            'nama_item' => json_encode($request->nama_item),
            'berat' => json_encode($request->berat),
            'harga' => json_encode($request->harga),
        ]);
        return redirect('admin-laundry/kontrak/create')->with('success', 'Data Berhasi Diupdate !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Kontrak  $kontrak
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        Kontrak::where('id', $id)->delete();
        return redirect('admin-laundry/kontrak')->with('error', 'Data Berhasi Dihapus !');
    }
}

app/Http/Controllers/AdminLaundryController.php
<?php

namespace App\Http\Controllers;

use App\Model\AdminLaundry;
use Illuminate\Http\Request;

class AdminLaundryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin-laundry.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
        /**
     * Display the specified resource.
     *
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
    public function show(AdminLaundry $adminLaundry)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
    public function edit(AdminLaundry $adminLaundry)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AdminLaundry $adminLaundry)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\AdminLaundry  $adminLaundry
     * @return \Illuminate\Http\Response
     */
}

resources/views/admin-laundry/kontrak/addItem.blade.php
<div class="row" style="margin-top:10px" id="input-{{ $key }}">
    <div class="col-md-2">
        <input type="text" class="form-control" name="kode_item[[{{$key}}]]" id="myorders">
    </div>
    <div class="col-md-4">
        <input type="text" class="form-control" name="nama_item[[{{$key}}]]" id="myorders">
    </div>
    <div class="col-md-2">
        <input type="number" class="form-control" name="berat[[{{$key}}]]" id="myorders">
    </div>
    <div class="col-md-2">
        <input type="number" class="form-control" name="harga[[{{$key}}]]" id="myorders">
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-danger" onclick="$(this).removeItem('#input-{{ $key }}')">x</button>
    </div>
</div>

resources/views/admin-laundry/kontrak/create.blade.php
@php
    $date = date('Y-m-d');    
    $jam = date('H:i:s');    
@endphp

@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Kontrak - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.index') }}">Dashboard</a>
			</div>
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.kontrak.index') }}">Kontrak</a>
			</div>
			<div class="breadcrumb-item active">
				<a>Create</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('/admin') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('admin.laundry.pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup & Delivery Boy"><i class="fas fa-user"></i><span>Pickup & Delivery Boy</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Client"><i class="fas fa-user"></i><span>Maintenance Client</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Kontrak"><i class="fas fa-file"></i><span>Maintenance Kontrak</span></a></li>
    <li><a class="nav-link" href="{{ route('users') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Management User"><i class="fas fa-users"></i><span>Management User</span></a></li>
   </ul>
@endsection

@section('content')
<form action="{{ route('admin.laundry.kontrak.store') }}" method="POST"> 
    @csrf
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
            <div class="row">

                <div class="col-md-12">
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">No Kontrak</label>
                        <div class="col-md-7">
                            <input type="text" name="no_kontrak" class="form-control" required="" value="" >
                        </div>
                    </div>  
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Client</label>
                        <div class="col-md-7">
                            <input type="text" name="client" class="form-control" required="" value="" >
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row mb-6">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Periode Kontrak Dari Tanggal</label>
                                <div class="col-md-7">
                                    <input type="date" name="periode_kontrak_mulai" class="form-control" required="" value="" >
                                </div>
                            </div>  
                        </div> 
                        <div class="col-md-6">
                            <div class="form-group row mb-6">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Sampai Tanggal</label>
                                <div class="col-md-7">
                                    <input type="date" name="periode_kontrak_akhir" class="form-control" required="" value="" >
                                </div>
                            </div>  
                        </div>    
                    </div>  
                     
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jenis Kegiatan</label>
                        <div class="col-md-7">
                            <input type="text" name="jenis_kegiatan" class="form-control" required="" value="" >
                        </div>
                    </div>  
                    
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-5">
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Kuota Minimal / Bln</label>
                                <div class="col-md-4">
                                <input type="number" name="kuota_minimal" class="form-control" required="" value="">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group row mb-2">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Berat Minimal / Bln</label>
                                <div class="col-md-4">
                                <input type="number" name="berat_minimal" class="form-control" required="" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Periode Tagihan</label>
                                <div class="col-md-7">
                                    <input type="text" name="periode_tagihan" class="form-control" required="" value="" >
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Terbit Invoice</label>
                                <div class="col-md-7">
                                <input type="text" name="terbit_invoice" class="form-control" required="" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jatuh Tempo</label>
                                <div class="col-md-7">
                                    <input type="date" name="jatuh_tempo" class="form-control" required="" value="" >
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Blokir Pickup</label>
                                <div class="col-md-7">
                                <input type="text" name="blokir_pickup" class="form-control" required="" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="card-title">
                        <h5>Item yang Disepakati Dalam Kontrak Ini</h5>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-2">
                            <h6 class="text-center">Kode Item</h6>
                            <input type="text" class="form-control" name="kode_item[0]" id="myorders">
                        </div>
                        <div class="col-md-4">
                            <h6 class="text-center">Nama Item</h6>
                            <input type="text" class="form-control" name="nama_item[0]" id="myorders">
                        </div>
                        <div class="col-md-2">
                            <h6 class="text-center">Berat (gr)</h6>
                            <input type="number" class="form-control" name="berat[0]" id="myorders">
                        </div>
                        <div class="col-md-2">
                            <h6 class="text-center">Harga /gr</h6>
                            <input type="number" class="form-control" name="harga[0]" id="myorders">
                        </div>
                        <div class="col-md-1">
                            <button type="button" class="btn btn-success" id="add-order"><i class="fa fa-plus"></i></button>
                        </div>
                    </div>
                    {{-- append ajax --}}
                    <div id="input-list"> </div>
                    <input type="hidden" id="key" value="0">
                    <br>
                
                    <div class="card-footer text-right">
                        <a href="{{ route('admin.laundry.kontrak.index') }}" class="btn btn-danger btn-lg">Batal</a>
                        <button class="btn btn-primary btn-lg">Simpan</button>
                    </div>
                </form>
                    
                </div>
      </div>
    </div>
</div>
@endsection

@section('script')
  
    <script>
        $(document).ready(function(){

            var key_input = $("#key").val();

            $("#add-order").on("click", function(e){ 

                e.preventDefault();

                key_input++;

                var url = '/ajax/get-item'

                var data = {
                    key:key_input
                }
                
                $.ajax({
                    url:url,
                    data:data,
                    type:"POST",
                    success:function(result){
                        $("#input-list").append(result.html);
                        $("#key").val(result.key);
                    }
                })
            
            });
        });

        $.fn.removeItem = function(id){
            $(id).remove();
        }

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        
    </script>

@endsection

resources/views/admin-laundry/kontrak/index.blade.php
@extends('templates.stisla')

@section('title', 'Laundry')

@section('header')
	<div class="section-header">
		<h1>Admin - Dashboard</h1>
		<div class="section-header-breadcrumb">
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.index') }}">Dashboard</a>
			</div>
			<div class="breadcrumb-item active">
				<a href="{{ route('admin.laundry.pickup.boy.index') }}">Pickup Boy</a>
			</div>
			<div class="breadcrumb-item active">
				<a>Create</a>
			</div>
		</div>
	</div>
@endsection
    
@section('sidebar-menu')
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li><a class="nav-link" href="{{ url('/admin') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Dashboard"><i class="fas fa-home"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">List</li>
    <li><a class="nav-link" href="{{ route('admin.laundry.pickup.boy.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Pickup & Delivery Boy"><i class="fas fa-user"></i><span>Pickup & Delivery Boy</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Client"><i class="fas fa-user"></i><span>Maintenance Client</span></a></li>
    <li><a class="nav-link" href="{{ route('admin.laundry.client.index') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Maintenance Kontrak"><i class="fas fa-file"></i><span>Maintenance Kontrak</span></a></li>
    <li><a class="nav-link" href="{{ route('users') }}" data-toggle="tooltip" data-placement="right" title data-original-title="Management User"><i class="fas fa-users"></i><span>Management User</span></a></li>
   </ul>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">  
              <table class="table table-bordered table-striped table-hover" id="dabel">
                <a href="{{ route('admin.laundry.kontrak.create') }}" class="a btn btn-info btn-lg float-right"><i class="fa fa-plus"></i></a>
                <br>
                <h4 class="card-title">Maintenance Kontrak</h4>

                  <thead class="text-center">
                      <tr>
                          <th>No</th>
                          <th>No Kontrak</th>
                          <th>Perusahaan Client</th>
                          <th>Dari Tanggal</th>
                          <th>Sampai Tanggal</th>
                          <th>Jenis</th>
                          <th>Action</th>
                      </tr>
                  </thead>
                  <tbody>
                      
                      @foreach ($data as $val)
                          {{-- @php
                              $item = json_decode($val->nama_item);
                          @endphp --}}
                    {{-- @foreach ($item as $file)
                          {{$file}},
                          @endforeach --}}
                        <tr>
                            <td>{{ $loop->index+1 }}</td>
                            <td>{{ $val->no_kontrak }}</td>
                            <td>{{ $val->client }}</td>
                            <td>{{ $val->periode_kontrak_mulai }}</td>
                            <td>{{ $val->periode_kontrak_akhir }}</td>
                            <td>{{ $val->jenis_kegiatan }}</td>
                            <td>
                              <a href="{{ url('admin-laundry/kontrak/edit/'.$val->id) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
                              {{-- <a href="{{ url('admin-laundry/kontrak/delete/'.$val->id) }}" class="btn btn-danger"><i class="fa fa-trash"></i></a> --}}
                            </td>
                          </tr>
                      @endforeach
                  </tbody>
              </table>  
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection